maint: fix 'make check' of legacy makefile
... additionally spotted a suspicious message during 'make check', it
may be a regression:

Error: slplug.c-types.dot:1469: syntax error near line 1469